# Generated by Django 3.2.22 on 2023-10-27 21:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/deafult-images/profile.png', max_length=255, verbose_name='image'),
        ),
    ]
