# Generated by Django 3.2.22 on 2023-10-27 22:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='static/default-images/mqs831nya0econccdhgs', max_length=255, verbose_name='image'),
        ),
    ]
