# Generated by Django 3.2.22 on 2023-10-27 22:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dc9f7ztkr/image/upload/v1698444280/b868mv6vciq3m4fixf3i.png', max_length=255, verbose_name='image'),
        ),
    ]
