# Generated by Django 3.2.22 on 2023-11-01 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactModel',
        ),
    ]
